version: 2.1

orbs:
  python: circleci/python@2.0.3

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout # checkout source code
      - python/install-packages:
          pkg-manager: pip
      - run:
          command: ls
          name: Test

workflows:
  main:
    jobs:
      - build-and-test
