version: 2.1

orbs:
  python: circleci/python@2.1.1

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Run tests
          command: python -m unittest
      - persist_to_workspace:
          root: ~/project
          paths:
            - .

workflows:
  main:
    jobs:
      - build-and-test
